# This file can be used for thesting the API with a dedicated Visual Studio Code extension.


## Execute Log In
POST http://localhost:3001/api/sessions HTTP/1.1
content-type: application/json

{
    "username": "marco.profilo@gmail.com",
    "password": "1234"
}
###

## Execute Log In
POST http://localhost:3001/api/sessions HTTP/1.1
content-type: application/json

{
    "username": "francesca.bianchi@gmail.com",
    "password": "abcd"
}
###

## Execute Log In
POST http://localhost:3001/api/sessions HTTP/1.1
content-type: application/json

{
    "username": "federico.grasso@gmail.com",
    "password": "abcd"
}
###

## Controllo se l'utente è ancora loggato
GET http://localhost:3001/api/sessions/current HTTP/1.1
###

## Execute Log Out.
DELETE http://localhost:3001/api/sessions/current HTTP/1.1
###

## Recupera tutte le proposte di uno user dallo userId
GET http://localhost:3001/api/proposals/2 HTTP/1.1
###

## Crea una nuova proposta (con tutti i campi eccetto l'ID)
POST http://localhost:3001/api/proposals HTTP/1.1
content-type: application/json

{
    "user_id": 2,
    "description": "Costruzione campi sportivi",
    "cost": 1800
}
###

## Modifica la prima proposta
PUT http://localhost:3001/api/proposals/1 HTTP/1.1
content-type: application/json

{
    "user_id": 2,
    "description": "Acquisto nuovi libri per la biblioteca comunale",
    "cost": 400
}
###

## Eliminazione terza proposta
DELETE http://localhost:3001/api/proposals/14 HTTP/1.1
###

## Retrieving all proposal
GET http://localhost:3001/api/proposals HTTP/1.1
###

## Vota la seconda proposta
POST http://localhost:3001/api/proposals/2/vote HTTP/1.1
content-type: application/json

{
    "score": 3
}
###