# This file can be used for thesting the API with a dedicated Visual Studio Code extension.


## Execute Log In
POST http://localhost:3001/api/sessions HTTP/1.1
content-type: application/json

{
    "username": "marco.profilo@gmail.com",
    "password": "1234"
}
###

## Execute Log In
POST http://localhost:3001/api/sessions HTTP/1.1
content-type: application/json

{
    "username": "francesca.bianchi@gmail.com",
    "password": "abcd"
}
###

## Execute Log In
POST http://localhost:3001/api/sessions HTTP/1.1
content-type: application/json

{
    "username": "federico.grasso@gmail.com",
    "password": "abcd"
}
###

## Controllo se l'utente è ancora loggato
GET http://localhost:3001/api/sessions/current HTTP/1.1
###

## Execute Log Out.
DELETE http://localhost:3001/api/sessions/current HTTP/1.1
###

## Inizializza il budget e la fase settandola a 0
POST http://localhost:3001/api/init HTTP/1.1
content-type: application/json

{
    "amount": 3000
}
###

## Recupera il budget e la fase attuali
GET http://localhost:3001/api/budgetandfase HTTP/1.1
###

## Avanza di fase
PUT http://localhost:3001/api/nextfase HTTP/1.1
###

## Recupera tutte le proposte di uno user dallo userId
GET http://localhost:3001/api/proposals/2 HTTP/1.1
###

## Recupera la proposta in base al suo id
GET http://localhost:3001/api/proposals/id/6 HTTP/1.1
###

## Crea una nuova proposta (con tutti i campi eccetto l'ID)
POST http://localhost:3001/api/proposals HTTP/1.1
content-type: application/json

{
    "description": "Bonifica zonaa paludosa",
    "cost": 1000
}
###

## Modifica la prima proposta
PUT http://localhost:3001/api/proposals/1 HTTP/1.1
content-type: application/json

{
    "description": "Acquisto nuovi libri per la biblioteca1",
    "cost": 600
}
###

## Eliminazione prima proposta
DELETE http://localhost:3001/api/proposals/1 HTTP/1.1
###

## Recupera tutte le proposte
GET http://localhost:3001/api/proposals HTTP/1.1
###

## Vota la terza proposta
POST http://localhost:3001/api/proposals/64/vote HTTP/1.1
content-type: application/json

{
    "score": 2
}
###

## Recupera le proposte votate dall'utente
GET http://localhost:3001/api/proposals/voted/2 HTTP/1.1
###

## Elimina la votazione di una proposta precedentemente votata dall'utente
DELETE http://localhost:3001/api/proposals/voted/delete/64 HTTP/1.1
###

## Recupera le proposte ordinate in base allo score_totale
GET http://localhost:3001/api/proposal/ordered HTTP/1.1
###

## Approva proposte in base al budget
PUT http://localhost:3001/api/proposal/approve HTTP/1.1
###

## Recupera le proposte approvate ordinate in base allo score_totale
GET http://localhost:3001/api/proposal/approved HTTP/1.1
###

## Recupera le proposte non approvate ordinate in base allo score_totale
GET http://localhost:3001/api/proposal/notApproved HTTP/1.1
###

## Riavvia il processo - Eliminazione delle proposte
DELETE http://localhost:3001/api/proposal/restart HTTP/1.1
###

